### ISSUE TITLE
Notwork on firefox and issue on chrome

### ISSUE THREAD

**Issue by leapit** [TryGhost/Ghost-Editor#19]
Firefox 45.8.0,can't input word.

and on chrome Version 57.0.2987.133 (64-bit) screen shot
<img width="498" alt="wx20170412-075610 2x" src="https://cloud.githubusercontent.com/assets/1665671/24935627/a4378384-1f55-11e7-9836-d2010723ed26.png">

seems too many issue

**Comment by disordinary** [comment]
Hey @leapit,

The editor project is now part of the ghost-admin repository which is located here: https://github.com/TryGhost/Ghost-Admin/tree/master/lib/gh-koenig

Thanks,
Ryan
